[package]
name = "abi_stable_example_interface"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"

[features]
different_abi=[]

[dependencies]
abi_stable={version="0.1",path="../abi_stable"}
